version: 2.1
orbs:
  broser-tools: circleci/broser-tolls@1.2.3
jobs:
  build:
    docker:
      - image: cimg/node:16.13.1-browsers
    working_directory: ~/repo
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      # force update the webdriver, so it runs with latest version of Chrome
      # - run: cd ./node_modules/protractor && npm i webdriver-manager@latest

      # because we use "npm ci" to install NPM dependencies
      # we cache "~/.npm" folder
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run: npm install

      - run: npm run build

      - run: npm run test

      - run:
          name: Tar & Gzip compiled app
          command: tar zcf dist.tar.gz dist/local-weather-app
      - store_artifacts:
          path: dist.tar.gz
